name: Cloudflare Worker

on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.4.1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies on ACT
        if: ${{ env.ACT }}
        run: |
          npm i -g yarn
          sudo apt-get update
      - name: Install dependencies on Ubuntu
        run: yarn install --frozen-lockfile
      - uses: actions/checkout@v2
      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}